log:
  name: "novacancy"
  directory: "logs"
  level: 10
#  level: 20
  suffix: "%Y-%m-%d"
  file_name: "{name}-{date:%Y-%m-%d}.log"
  format: "%(levelname)s\t%(asctime)s\t[%(name)s, %(filename)s:%(lineno)d]\t%(message)s"

devices:
  max_weight: -700000
  weights:
    "0": 0.1
    "1": 0.1
    "2": 0.1
  distances:
    "0": 160.0
    "1": 160.0
    "2": 160.0

groups:
  west_wing:
    devices: ["0", "1", "2"]
    bigsign: "3"
  bathrooms_101:
    devices: ["4", "5"]
    bigsign: "6"
